[build]
  publish = "client"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]

# Set a global timeout for all functions
[functions.default]
  timeout_in_seconds = 100
